spring:
  datasource:
    url: jdbc:mysql://192.168.65.128:3306/springSecurity?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 190715zcy
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.65.128
    port: 6379
    password: 190715zcy